### ISSUE TITLE
Slow pdist in PTV_analysis_TNTI/duda_r.m

### ISSUE THREAD

**Issue by MarkBaevsky** [MarkBaevsky/PTV_analysis_TNTI#2]
Alex,
The pdist approach seems to be slow. Can you tell me if I did something wrong in this function?

**Comment by alexlib** [comment]
see the latest commit cd8c0453 
the main changes are in the commit message: 
use dR as a vector, otherwise you repeat pdist call many times
coped some code from squareform and saved some time. 
tolerance of a search shall be smaller as it makes enormous search
loop of vector scalar products is now vectorized by vector product, diag and mean (we need the average, right? )
